### ISSUE TITLE
Change Cell Size ( or number of items in one column)

### ISSUE THREAD

**Issue by chlebta** [fmitech/FMMosaicLayout#4]
Hello, thank's this really simple and great Library and I need to know how can I change the cells size and use my costum size.
Also I've noticed that the number of cells in rows is always multiplier of 2 (2 cells, 4 cells, 8 cells ... in a row) and the big cell size is 2 cells for width and height. 
So it will be more nicer if you allows user to define the number of cell in row and the big cell size (for example 3cell for height and 4 for width).
Also I'm ready to contribute in this project

**Comment by JVillella** [comment]
Hey there @chlebta you are right about the cell column counts being multiples of 2. More information about how the algorithm works can be found on the blog post I've linked from the README. This multiples of 2 behaviour goes hand in hand with the layout algorithm and changing it to something else would require a different process.

Now about the column sizes - they can be changed by implementing `collectionView:layout:numberOfColumnsInSection:` in the `FMMosiacLayoutDelegate`. Higher column counts mean smaller cell width.

Happy coding!

**Comment by chlebta** [comment]
@JVillella  This Will change the height from small to double the height of small cell thats all but i want to use custom height and width. Also the blog link doesn't work .
 This is Example what of I I'm talking about : 
![capture d ecran 2015-03-14 a 10 55 44](https://cloud.githubusercontent.com/assets/1204608/6651215/bdd4113c-ca38-11e4-904c-4fb230d81080.png)

*So the screen will be divide into 3 column.
*Each column will hold one items.
*the big cell items size will be the double.

I'm new on objective and IOS world but Algorithm and mathematic I got great skills, so  if you don't mind we can work's on optimizing this library  ?

**Comment by JVillella** [comment]
I see what your saying. Many of us would benefit from more customizable mosaic sizing. If you'd like to try some experiments and see what you can do - that would be awesome! I think the [site](http://blog.vjeux.com/2012/image/image-layout-algorithm-facebook.html) is up now, give it another try.

**Comment by chlebta** [comment]
@JVillella  Yes the site work's now and I'm will give try to optimize this library and make it more simple and customizable :+1:  also can I get your email to talk directly and in case of trouble.

**Comment by JVillella** [comment]
That would be great thanks! My email is in the podspec of the repo's root. So that others can learn from your progress it may be best to keep our chats on this thread. I reply quickly either way.

**Comment by chlebta** [comment]
@JVillella  Hello, is there any rapid hack to add third type of Cell (where width = 2*Small Cell width ; and height = normal small Cell height) ?
Also can you make the code more commented I'm working on solution to make it more dynamic as we talked .

**Comment by JVillella** [comment]
The algorithm asks the `FMMosaicLayoutDelegate` for the _type_ of mosaic cell size (either `FMMosaicCellSizeBig`, or `FMMosaicCellSizeSmall` - half the size of big). This is done in:

```
- (FMMosaicCellSize)collectionView:(UICollectionView *)collectionView
                            layout:(FMMosaicLayout *)collectionViewLayout
  mosaicCellSizeForItemAtIndexPath:(NSIndexPath *)indexPath;
```

We work in columns, which again is provided by the delegate in:

```
- (NSInteger)collectionView:(UICollectionView *)collectionView
                     layout:(FMMosaicLayout *)collectionViewLayout
   numberOfColumnsInSection:(NSInteger)section;
```

We use a buffer to store small cells until we have 2 (enough to fill the width of a column). This is when we actually add it to our column heights array property (currently named `columnHeightsInSection`) and our layout attributes property (currently named `layoutAttributes`).

If we have leftover small cells after this process (because there weren't 2 to pair together) we handle them separately (see the commented code block about this).

The column heights property maintains the height of each column in each section. It's a 2D array - an array of sections, and heights per column in each section.

The majority of the rest of code deals with `UICollectionViewLayout` specifics. You said you were new to iOS and Objective-C. A book that helped me understand them better when I was learning was [iOS UICollectionView: The Complete Guide](http://www.amazon.ca/iOS-UICollectionView-Complete-Edition-Programming-ebook/dp/B00IHZKDCU) as well as this [article](http://www.objc.io/issue-5/collection-views-and-uidynamics.html) about combining `UICollectionView` and `UIDynamics`. It goes a lot into how the layouts work. Both resources are written by @AshFurrow.

---

> there any rapid hack to add third type of Cell (where width = 2*Small Cell width; and height = normal small Cell height)?

Yes this can be done. It's relatively similar to how the small cells are buffered and then added to those two properties (cell heights array, layout attributes). This shouldn't be hard to do - probably a few lines.

Good luck. Hope that helps!
